apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multus-cni
resources:
  - ./namespace.yaml
  - ./multus.yaml
  - ./cni.yaml
  - ./route-override.yaml
  - ./dhcp.yaml
  - ./networks.yaml
patches:
  - path: ./ds-patch.yaml