---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: route-override
  namespace: kube-system
  template:
    spec:
      containers:
        - name: route-override
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /host/opt/cni/bin