---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: cab-opnsense
 namespace: cilium
spec:
 nodeSelector:
   matchLabels:
    kubernetes.io/os: linux
 virtualRouters:
 - localASN: 64750
   exportPodCIDR: false
   serviceSelector:
      matchExpressions:
        - {key: io.cilium/announce, operator: NotIn, values: ['dummy-value']}
   serviceAdvertisements:
      - LoadBalancerIP
   neighbors:
    - peerAddress: '10.7.0.1/32'
      peerASN: 64700
      gracefulRestart:
          enabled: true
          restartTimeSeconds: 60
      families: # https://docs.cilium.io/en/latest/network/bgp-control-plane/#address-families
      - afi: ipv4 # disable ipv6 advertisement to work around https://github.com/cilium/cilium/issues/30367/
        safi: unicast
      peerPort: 179
      eBGPMultihopTTL: 1
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30