# https://github.com/cilium/cilium/blob/v1.16.6/install/kubernetes/cilium/values.yaml
cni:
  exclusive: false # true renames multus to multus_cilium.bak, ie we need false for multus to work

securityContext:
  privileged: true #https://github.com/siderolabs/talos/issues/5948#issuecomment-1190245553
#   capabilities: # https://www.talos.dev/v1.6/kubernetes-guides/network/deploying-cilium/#without-kube-proxy
#     ciliumAgent: [ CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID ]
#     cleanCiliumState: [ NET_ADMIN,SYS_ADMIN,SYS_RESOURCE ]
# cgroup: # https://www.talos.dev/v1.6/kubernetes-guides/network/deploying-cilium/#without-kube-proxy
#   autoMount:
#     enabled: false
#     hostRoot: "/sys/fs/cgroup"

# tunnel: "disabled" # disabls vxlan encapsulation, which is required for pod-gateway https://github.com/k8s-at-home/charts/issues/1633#issuecomment-1168361095
# superseded (and conflicts with!) routing-mode=native (default value) in v1.14
routingMode: "native"

autoDirectNodeRoutes: true # enable auto generated routes, if all cluster nodes are in same L2 network (subnet)
ipv4NativeRoutingCIDR: "10.244.0.0/16" # ClusterConfig.network.podSubnets
ipam: # https://docs.cilium.io/en/stable/network/concepts/ipam/#address-management
  mode: kubernetes # https://docs.cilium.io/en/stable/network/concepts/ipam/kubernetes/
  operator:
    clusterPoolIPv4PodCIDRList:
    - "10.244.0.0/16" # ClusterConfig.network.podSubnets

kubeProxyReplacement: true # aka 'strict' in <=v1.13, required for DSR, Bandwidth Manager, XDP Acceleration https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/#kube-proxy-hybrid-modes

# bpf:
#   # 2025-01: below setting breaks cilium (level=fatal msg="failed to start: BPF bandwidth manager's BBR setup requires BPF host routing.")
#   # so we'll have to disable on talos side (machine.features.hostDNS.forwardKubeDNSToHost: false)
#   hostLegacyRouting: true # talos compatibility post v1.16.6 https://github.com/cilium/cilium/pull/36852 | https://www.talos.dev/v1.9/kubernetes-guides/network/deploying-cilium/#known-issues

# 2024-03: wrong values here brick cluster networking, including ability to read pod logs via eg k9s (red herring tls errors)
k8sServiceHost: "10.7.0.30" # usually the first ip in the Service range, NetworkConfig.interfaces.vip would also work except creates chicken/egg issue (vip doesnt function until first node is healthy)
k8sServicePort: "6443"
# k8sServiceHost: "localhost" # kubePrism compatibility https://www.talos.dev/v1.6/kubernetes-guides/network/deploying-cilium/#without-kube-proxy
# k8sServicePort: "7445"

bandwidthManager: # https://docs.cilium.io/en/stable/operations/performance/tuning/#bandwidth-manager
  enabled: true
  bbr: true # requires kernel => 5.18 https://isovalent.com/blog/post/accelerate-network-performance-with-cilium-bbr/

loadBalancer: # https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/#loadbalancer-nodeport-xdp-acceleration
  # acceleration: native # requires NIC to support this function; enterprise ones do, vmxnet3 doesn't but is in flux (Q3 2022 kernel patch request - https://lore.kernel.org/all/202207082309.Qgnp3toD-lkp@intel.com/)
  mode: hybrid # https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/#hybrid-dsr-and-snat-mode
  algorithm: maglev # https://docs.cilium.io/en/latest/network/kubernetes/kubeproxy-free/#maglev

bgp: # legacy (<=v1.12) implementation
  enabled: false

bgpControlPlane: # new in v1.13
  enabled: true

# containerRuntime: # deprecated in v1.16
#   integration: containerd # default is none

prometheus:
  enabled: true # https://docs.cilium.io/en/stable/observability/metrics/

hubble:
  enabled: true # 1-15% performance hit https://docs.cilium.io/en/stable/operations/performance/tuning/#hubble
  relay:
    enabled: true # required for multi-node support
    rollOutPods: true # auto-restart pods when config is updated
  metrics: # if not specified, no metrics are collected
    enabled:
    - dns:query;ignoreAAAA
    - tcp
    - flow
    - icmp
    - http
    - port-distribution
    # - httpV2:exemplars=true
    # - labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction
    enableOpenMetrics: true # https://docs.cilium.io/en/stable/observability/metrics/#openmetrics
  ui:
    enabled: true # deploy a web UI pod
    rollOutPods: true # auto-restart pods when config is updated
    ingress:
      enabled: true # publish it (default access via 'cilium hubble ui' CLI port forward)
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - hubble.${INT_FQDN_I-$DEFAULT_FQDN}
      tls:
        - hosts:
            - hubble.${INT_FQDN_I-$DEFAULT_FQDN}
  tls:
    auto:
      method: helm # helm, cronJob, certmanager all require argocd ignores to avoid regen on push

enableXTSocketFallback: false # https://www.talos.dev/latest/kubernetes-guides/network/deploying-cilium/#other-things-to-know

egressGateway:
  enabled: false
ipv6:
  enabled: false
ipvlan:
  enabled: false

operator:
  replicas: 1 # cli deploy defaults to 1, chart to 2
  # priorityClassName: cluster << causes cilium pods to fail during bootstrap, because priorityClass'es are instantiated (via argocd) later
  prometheus:
    enabled: true
  rollOutPods: true # auto-restart pods when config is updated
  # priorityClassName: cluster # TODO: requires PriorityClass manifest to be deployed prior to cilium's chart
rollOutCiliumPods: true # auto-restart pods when config is updated

# cluster:
#   id: 0 #0 means disable clustermesh