apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: cbgpp-policy
 namespace: cilium
spec:
 nodeSelector:
   matchLabels:
    kubernetes.io/os: linux
 virtualRouters:
 - localASN: 64750
   exportPodCIDR: false
   serviceSelector:
      matchExpressions:
        - {key: io.cilium/announce, operator: NotIn, values: ['dummy-value']}
   serviceAdvertisements:
      - LoadBalancerIP
   neighbors:
    - peerAddress: '10.10.97.1/32'
      peerASN: 64700
      gracefulRestart:
          enabled: true
          restartTimeSeconds: 60
      families:
      - afi: ipv4
        safi: unicast
      peerPort: 179
      eBGPMultihopTTL: 1
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
    - peerAddress: '10.10.98.1/32'
      peerASN: 64700
      gracefulRestart:
          enabled: true
          restartTimeSeconds: 60
      families:
      - afi: ipv4
        safi: unicast
      peerPort: 179
      eBGPMultihopTTL: 1
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30

