apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networks.yaml
  - daemonset-thick.yaml
patches:
  # Patch netns hostPath as per https://www.talos.dev/v1.10/kubernetes-guides/network/multus/#patching-the-daemonset
  - patch: |
      - op: replace
        path: /spec/template/spec/volumes/host-run-netns/hostPath
        value:
          path: /var/run/netns/
    target:
      kind: DaemonSet
      name: kube-multus-ds
      namespace: kube-system