apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networks.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/volumes/host-run-netns/hostPath/path
        value: /var/run/netns/
    target:
      kind: DaemonSet
      name: kube-multus-ds
      namespace: kube-system