apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networks.yaml
  - ds.yaml
patches:
  # Patch netns hostPath as per https://www.talos.dev/v1.10/kubernetes-guides/network/multus/#patching-the-daemonset
  - patch: |
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: kube-multus-ds
        namespace: kube-system
      spec:
        template:
          spec:
            volumes:
              - name: host-run-netns
                hostPath:
                  path: /var/run/netns/
    target:
      kind: DaemonSet
      name: kube-multus-ds
      namespace: kube-system